[workspace]

exclude = [
        "sudoku-risc0",
        "sudoku-halo",
        "fib-miden"
]

[package]
name = "shootout"
version = "0.1.0"
edition = "2021"

[dependencies]
sudoku_risc = { path = "sudoku-risc0" }
sudoku_halo = { path = "sudoku-halo" }
fib-miden   = { path = "fib-miden"}
criterion   = "0.3"

[profile.release]
debug = 1

[[bench]]
name = "my_benchmark"
harness = false
path = "src/main.rs"

# TODO This is dumb that we need to include it here or else rust freaks out ☹
[patch.crates-io]
ark-serialize = { git = "https://github.com/simonmasson/algebra", rev = "e2ea75c" }
ark-ff        = { git = "https://github.com/simonmasson/algebra", rev = "e2ea75c" }
ark-ec        = { git = "https://github.com/simonmasson/algebra", rev = "e2ea75c" }
ark-std       = { git = "https://github.com/arkworks-rs/std/"   , rev = "2b3568f" }